#!/bin/bash

echo "===========Chasm Installing======= " && sleep 1

# Constants
folder_to_check="$HOME/tokio-docker/"
# Declare varibles
scout_name=""
scout_id=""
web_api_key=""
web_hook_ip=""
groq_api_key=""  
port=3001

while [ -z "$scout_name" ] || [ -z "$scout_id" ] || [ -z "$web_api_key" ] || [ -z "$web_hook_ip" ] || [ -z "$groq_api_key" ]; do
    read -p "Enter SCOUT_NAME: " scout_name
    read -p "Enter SCOUT_UID: " scout_id
    read -p "Enter WEBHOOK_API_KEY: " web_api_key
    read -p "Enter WEBHOOK_URL: " web_hook_ip
    read -p "Enter GROQ_API_KEY: " groq_api_key
    read -p "Enter PORT: " port

    if [ -z "$reward" ] || [ -z "$evm_address" ] || [ -z "$evm_private_key" ]; then
        echo "Please fill full information."
    fi
done

sudo apt update && apt upgrade -y

sudo apt install firewalld -y
sudo systemctl enable firewalld
sudo systemctl start firewalld
sudo firewall-cmd --permanent --zone=public --add-port="$"/tcp
firewall-cmd --reload
